apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-board
  namespace: postapp
spec:
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: react-board-pod
  template:
    metadata:
      labels:
        app: react-board-pod
    spec:
      containers:
      - name: react-board-container
        image: dianaseong/reactboard:61241f8abe46d673b12876711f5b9707cf796be5
        ports:
        - containerPort: 80
